// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_URL: "https://local.kotohiro.com:3000" | "https://www.kotohiro.com";
	API_URL: "http://127.0.0.1:3658/m1/674502-646219-default" | "https://api.kotohiro.com";
}
