// Generated by Wrangler by running `wrangler types`

interface Env {
  APP_URL:
    | "https://local.kotohiro.com:3000"
    | "https://develop.kotohiro.com"
    | "https://staging.kotohiro.com"
    | "https://www.kotohiro.com";
  API_URL: "https://api-dev.kotohiro.com" | "https://api.kotohiro.com";
}
