name: Lint & Typecheck

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Lint & Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run typecheck
        env:
          CLOUDFLARE_ENV: develop
        run: pnpm typecheck

      - name: Run Lint
        run: pnpm lint
